### ISSUE TITLE
Besu on Kubernetes RPC endpoint shows as "Resource Not Found" when serving over HTTPS with Ingress

### ISSUE THREAD

**Issue by YazzyYaz** [hyperledger/besu#1084]
### Description
I have a Besu statefulset manifest file and a service yaml file, and can get the endpoint directly from the IP provided by the service yaml file. So, doing a curl on the Besu endpoint served via the Service file allows me to get latest block data.

My issue stems from when I try to use the Kubernetes Ingress to grab that service endpoint and serve it over HTTPS on a domain. By then, it shows "Resource Not Found".

On Google Kubernetes Engine, I've set the health check for the Ingress file and that endpoint for the 8545 port for Besu to do a health check on `/liveness` and the health check completes normally and no issue is found. The system is found to be healthy because my Besu endpoint is synced up and can serve on HTTP endpoint provided by the Service manifest. It's just odd behavior when it tries to serve it via ingress on HTTPS.

Here is the StatefulSet manifest yaml file:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: classic-besu 
  namespace: ethercluster
  labels:
    app: classic-besu
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: classic-besu
  serviceName: classic-besu
  template:
    metadata:
      name: classic-besu
      labels:
        app: classic-besu
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: besu
          image: "hyperledger/besu:latest"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          args: 
          - "--network=classic"
          - "--sync-mode=FAST"
          - "--data-path=/classic-besu-data"
          - "--node-private-key-file=/classic-besu-data/keys"
          - "--rpc-http-enabled" 
          - "--rpc-ws-enabled"
          - "--host-whitelist=*"
          - "--rpc-http-cors-origins=*"
          - "--p2p-host=35.223.202.158"
          - "--p2p-port=30303"
          - "--rpc-http-host=0.0.0.0"
          - "--rpc-http-port=8545"
          - "--nat-method=KUBERNETES"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 8546
              protocol: TCP
              name: ws-port
            - containerPort: 443
              protocol: TCP
              name: https
          volumeMounts:
            - name: classic-besu-data
              mountPath: /classic-besu-data
      volumes:
       - name: classic-besu-data
  volumeClaimTemplates:
    - metadata:
        name: classic-besu-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-besu-ssd"
        resources:
          requests:
            storage: 800Gi
```

The Service YAML manifest is:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: classic-besu
  name: classic-besu
  namespace: ethercluster
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: classic-besu
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
  - name: rpc-endpoint
    port: 8545
    protocol: TCP
    targetPort: 8545
  - name: ws-endpoint
    port: 8546
    protocol: TCP
    targetPort: 8546
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  sessionAffinity: ClientIP
```

The basic command in the deployment manifest for Besu that references the hardcoded IP address "35.223.202.158" (which is generated by the Service yaml manifest provided) is the following command:
```
besu --network=classic --sync-mode=FAST --data-path=/classic-besu-data --node-private-key-file=/classic-besu-data/keys --rpc-http-enabled --rpc-ws-enabled --host-whitelist=* --rpc-http-cors-origins=* --p2p-host=35.223.202.158
--p2p-port=30303 --rpc-http-host=0.0.0.0 --rpc-http-port=8545 --nat-method=KUBERNETES
```

The Ingress File has the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-eth
    namespace: ethercluster
    annotations:
        kubernetes.io/ingress.global-static-ip-name: ethercluster-address
        kubernetes.io/ingress.allow-http: "false"
        kubernetes.io/ingress.class: "gce"
        nginx.org/websocket-services: "ws-svc"
        ingress.kubernetes.io/enable-ssl-chain-completion: "false"
        ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
spec:
    tls:
      - hosts:
        - www.ethercluster.com
        secretName: tls-ethercluster
    backend:
      serviceName: ethercluster-site
      servicePort: 8080
    rules:
    - host: www.ethercluster.com
      http:
        paths:
        - path: /
          backend:
            serviceName: ethercluster-site
            servicePort: 8080
         - path: /besu-etc
          backend:
            serviceName: classic-besu
            servicePort: 8545
```

As you can see from this setup, running the following curl command on the IP Address (pre-ingress) gives the followign:
```
$ curl --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' \
-H "Content-Type: application/json" \
-X POST http://35.223.202.158:8545/

{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : "0xa1c72b"
}
```

Now, if I run it on the endpoint I specified for it: https://www.ethercluster.com/besu-etc, it'll show "Resource Not Found". Not sure if there's a missing config in Besu I need to setup in order to serve over SSL.

I have a similar setup with Parity that provides an RPC endpoint publicly over SSL. Just having difficulties communicating with Besu Statefulset.

### Steps to Reproduce (Bug)
1. Start a Kubernetes cluster using the above manifests and setup Ingress on GKE. Documentations for GKE and Kubernetes for this system are found here: https://docs.ethercluster.com/#/
2. Try to communicate with domain ssl endpoing for /besu-etc after sync.
3. Notice "Resource Not Found"

**Expected behavior:** [What you expect to happen]
Besu can be served over SSL from Kubernetes

**Actual behavior:** [What actually happens]

Besu can't be served over SSL from Kubernetes.

### Versions
* Software version: Latest Besu Release Candidate: https://hub.docker.com/layers/hyperledger/besu/latest/images/sha256-68b9df486d4837f055f5ca0680de8674f40be5ab45d4d5e590e496456c8e613d?context=explore
* Cloud VM, type, size: [Amazon Web Services I3-large] Google GKE
