### ISSUE TITLE
A contract which works on Rinkeby but not on Besu

### ISSUE THREAD

**Issue by soragXYZ** [hyperledger/besu#3345]
Hi everyone! I'm having a very weird behavior, I hope someone can help me

I deployed a simple smart contract for token vesting
This contract is working perfectly fine on Rinkeby and other test networks as you can see [here](https://rinkeby.etherscan.io/address/0x742e33F354Ef982385785280e16d53056bb75C36#code) 

I'm able to deploy the same contract on my private network as you can see [here](http://20.101.172.72/address/0x9d1008C11C17C00132aB18Ce0F9F3D695b0D4c15/contracts), but when trying to interact with the contract, each transaction get reverted without more information...
Moreover, it seems like the transaction consume every gas in the block, even if I have a crazy block gas limit of more than 10B... See [here](http://20.101.172.72/tx/0x88ae9ae364e93c03b11f88151b3fd66e4f0dc2e74536ce98b1b9cebd63d81a2d/internal-transactions) 

And I can't even send ethers to this contract, the transaction gets reverted too as you can see [here](http://20.101.172.72/tx/0x4bd24574ef93a55da08b77a7cfe22f4a7b8559647d62a2cf7f1e4d954dc27480/internal-transactions)

I have absolutely no idea about what is going on, and why this contract can't even receive some ethers

The contract was deployed using hardhat, Solidity v0.8.4
Here is my genesis.json, maybe my mistake is here:

```

rawGenesisConfig:
  genesis:
    config:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
      berlin: 0
      london: 0
      arrowGlacier: 0
      chainId: 1337
      constantinoplefixblock: 0
      ibft2:
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    nonce: '0x0'
    timestamp: '0x58ee40ba'
    gasLimit: '0x1fffffffffffff'
    difficulty: '0x1'
    mixHash: '0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365'
    coinbase: '0x0000000000000000000000000000000000000000'
    alloc:
      627306090abaB3A6e1400e9345bC60c78a8BEf57:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
      f17f52151EbEF6C7334FAD080c5704D77216b732:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
      fe3b557e8fb62b89f4916b721be55ceb828dbd73:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
      f90acf91bdab539aac3093e5c5b207b562354401:
        balance: '0x446c3b15f9926687d2c40534fdb564000000000000'
  blockchain:
    nodes:
      generate: true
      count: 4

```
