### ISSUE TITLE
Problem with deploying contract with EIP712 (block.chainid) via hardhat

### ISSUE THREAD

**Issue by PavelZavadskiy** [hyperledger/besu#3417]
There is a problem when deploying a hardhat contract with @openzeppelin/contracts/utils/cryptography/draft-EIP712.sol inheritance. Inside constructor EIP712 the block.chainid request on which the error occurs. When deploying to test networks Rinkeby, Kovan, Ropsten, etc. no such problem is observed.

besu/v22.1.0-RC4/windows-x86_64/oracle-java-17

**Comment by MadelineMurray** [comment]
hi @PavelZavadskiy - to clarify, you see the problem only when deploying to mainnet?

**Comment by PavelZavadskiy** [comment]
> to clarify, you see the problem only when deploying to mainnet

I have a problem when deploying in a besu. I run the besu like --network=dev.
Thanks

**Comment by macfarla** [comment]
@PavelZavadskiy can you share a minimal repo with the contract that you are deploying - that would make it a lot easier for us to reproduce.

**Comment by macfarla** [comment]
Also please include how are you deploying the contract?

**Comment by PavelZavadskiy** [comment]
https://github.com/PavelZavadskiy/ERC712_Test
npm i

**Comment by frankisawesome** [comment]
@PavelZavadskiy just wanted to confirm that you've tried deploying the same contract with other clients and only Besu has this issue?

**Comment by PavelZavadskiy** [comment]
> just wanted to confirm that you've tried deploying the same contract with other clients and only Besu has this issue?

Yes. The problem is only with the Besu.

**Comment by frankisawesome** [comment]
Which other clients have you tried?

**Comment by TrejGun** [comment]
this could be fixed by setting `"muirglacierblock": 0,` in your genesis file

https://besu.hyperledger.org/en/stable/HowTo/Configure/Genesis-File/

**Comment by frankisawesome** [comment]
@PavelZavadskiy a solution is given above - reopen if you're still having issues

**Comment by spaceh3ad** [comment]
@TrejGun which genesis file? I tried in `IBFT.genesis.json` and still have same error.

**Comment by TrejGun** [comment]
I believe you have to create one and pass it to the container

```yaml
  besu:
    container_name: besu
    user: root
    image: hyperledger/besu:latest
    environment:
      BESU_GENESIS_FILE: /var/lib/besu/genesis.json
      .....
    volumes:
      - ${BASE_PATH}/besu:/var/lib/besu
      - ${BASE_PATH}/gen-besu.json:/var/lib/besu/genesis.json
```
