### ISSUE TITLE
RPC performance regression since 22.4.0-RC2

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#3959]
### Description
We have had a report of RPC performance regression in besu after upgrading from 22.1.x to the latest quaarterly release versions:
![image (1).png](https://images.zenhubusercontent.com/6047871b4cf8bd5fa5c15d7b/33de5ae9-18ec-49d3-8519-172efcb5e265)

After some version bisecting it appears that the performance regression first appears in [22.4.0-RC2](https://github.com/hyperledger/besu/releases/tag/22.4.0-RC2):

![image.png](https://images.zenhubusercontent.com/6047871b4cf8bd5fa5c15d7b/789dfae9-26da-4377-b299-217747aa42d4)

As noted in the chart, versions since 22.4.0-RC2 show a significant latency in rpc response time for light RPC activity (1-2 requests per second).

### Acceptance Criteria
* identify and address the source of the rpc latency

### Steps to Reproduce (Bug)
To observe request latency spike on releases since 22.4.0-RC2
1. use the dev network resources attached to join as a non-validating node
2. at an average rate of 2 requests per second, issue a mix of RPC requests: 
  eth_getBlockByNumber Full and eth_getLogs Full 

**Expected behavior:** no regression in RPC performance

**Actual behavior:** request latency is unacceptable

**Frequency:** 100% reproducible with the aforementioned traffic

### Versions (Add all that apply)
* Software version: 22.4.0-RC2 +
* Java version: jdk 11
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
cloud k8s instance pod config:
```
- env:
    - name: JAVA_OPTS
      value: -Xmx16g
    - name: BESU_DATA_PATH
      value: /data
    - name: BESU_SYNC_MODE
      value: FULL
    - name: BESU_BOOTNODES
      value: enode://9cccbaae702d477c5fd4d704a2d6f92a90005f62de980b11b0d042877bf759774cf7d68d358c59427622e87538bc46afa1195d6ac12cb153d6771461c1830d1b@54.243.108.56:30303,enode://d6518f4f318a172158cf73c3e615c4eb488efb14c20b4a2f13570bf01092573222cd6935599a80017512457fb7f229cf6562f9d038b5d0dc98db95074d4a98b3@18.235.247.31:30303
    - name: BESU_RPC_HTTP_ENABLED
      value: "true"
    - name: BESU_RPC_HOST
      value: 0.0.0.0
    - name: BESU_RPC_HTTP_API
      value: ETH,NET,WEB3
    - name: BESU_P2P_PORT
      value: "30303"
    - name: BESU_HOST_ALLOWLIST
      value: '*'
    - name: BESU_NAT_METHOD
      value: NONE
    - name: BESU_GENESIS_FILE
      value: /genesis/genesis.json
    - name: BESU_P2P_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['dedicated.infura.io/pod-ip']
```
* System info - i3xl, with resource config:
```
    resources:
      requests:
        cpu: 3500m
        memory: 24Gi,
```
