### ISSUE TITLE
Free gas into Kubernetes private network not working

### ISSUE THREAD

**Issue by alexcostars** [hyperledger/besu#5541]
### Description

Hello,

I'm deploying a free gas private Besu Network, but Besu is requiring a gasPrice for my transactions.

### Steps to Reproduce

1. Configure a kubernetes private network with Helm, following this steps:

https://besu.hyperledger.org/en/stable/private-networks/tutorials/kubernetes/charts/#provision-with-helm-charts

2. Set `--min-gas-price=0` as a Besu parameter

```yaml
spec:
      containers:
      - args:
        - "exec\n/opt/besu/bin/besu \\\n  --config-file=/etc/besu/config.toml \\\n
          \ --Xdns-enabled=true --Xdns-update-enabled=true --Xnat-kube-service-name=besu-node-bootnode-1
          \\\n  --min-gas-price=0 \n
```
genesis chart:
```yaml
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0x47b760'
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
```

3. Sending raw transaction

With `0x0` gasPrice.

```json
{
    "jsonrpc":"2.0",
    "method":"eth_sendRawTransaction",
    "params":["0xf903b88080832dc6c08080b90368608060405234801561001057600080fd5b506000808190555033600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550610300806100686000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806306661abd1461005c5780638ada066e1461007a5780638da5cb5b1461009857806393d9df16146100b657806396f31713146100d2575b600080fd5b610064610102565b6040516100719190610182565b60405180910390f35b610082610108565b60405161008f9190610182565b60405180910390f35b6100a0610111565b6040516100ad91906101de565b60405180910390f35b6100d060048036038101906100cb919061022a565b610137565b005b6100ec60048036038101906100e7919061022a565b610152565b6040516100f99190610182565b60405180910390f35b60005481565b60008054905090565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b806000808282546101489190610286565b9250508190555050565b6000816000546101629190610286565b9050919050565b6000819050919050565b61017c81610169565b82525050565b60006020820190506101976000830184610173565b92915050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101c88261019d565b9050919050565b6101d8816101bd565b82525050565b60006020820190506101f360008301846101cf565b92915050565b600080fd5b61020781610169565b811461021257600080fd5b50565b600081359050610224816101fe565b92915050565b6000602082840312156102405761023f6101f9565b5b600061024e84828501610215565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600061029182610169565b915061029c83610169565b9250828201905082811215600083121683821260008412151617156102c4576102c3610257565b5b9291505056fea26469706673582212208a2890702d4caafca3f4af095cbb47e05443b77b8ff6d3dcfd64b6dd6c00efa664736f6c63430008120033820a96a02bd278f02f4bf942e4fb79a26f8489ef93aac65ea084b2f3ce3e87c6981cd348a04fe9cb75d89847d40baf6657b1d7d8b8b5ef4291defe050184388017611c2803"],
    "id":1
}
```

4. Error returned

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32009,
    "message": "Gas price below configured minimum gas price"
  }
}
```
I tried with a contract deploy and ether transfer, this error is showing in all situations.

### Logs
I don't know which log can help to describe this situation, but this is the `admin_nodeInfo`:

```json
{
  "jsonrpc": "2.0",
  "id": 51,
  "result": {
    "enode": "enode://fe46bd0d00e1422e0a020f71cca8e0b756ddac6998e32eba6c5589832faaf4e691640e02e97f5e3f5bc71665a53876ea23dc9b3984eefa4018d8dfdbf41adf58@0.0.0.0:30303",
    "listenAddr": "0.0.0.0:30303",
    "ip": "0.0.0.0",
    "name": "besu/v22.7.2/linux-x86_64/openjdk-java-11",
    "id": "fe46bd0d00e1422e0a020f71cca8e0b756ddac6998e32eba6c5589832faaf4e691640e02e97f5e3f5bc71665a53876ea23dc9b3984eefa4018d8dfdbf41adf58",
    "ports": {
      "discovery": 30303,
      "listener": 30303
    },
    "protocols": {
      "eth": {
        "config": {
          "chainId": 1337,
          "homesteadBlock": 0,
          "eip150Block": 0,
          "eip158Block": 0,
          "byzantiumBlock": 0,
          "constantinopleBlock": 0,
          "petersburgBlock": 0,
          "istanbulBlock": 0,
          "muirGlacierBlock": 0,
          "berlinBlock": 0,
          "londonBlock": 0,
          "qbft": {
            "epochLength": 30000,
            "blockPeriodSeconds": 10,
            "requestTimeoutSeconds": 20
          }
        },
        "difficulty": 13505,
        "genesis": "0xd1b2bc164d873cee0a39085a72ad03e27bb028fb36352e986346da6720a0468a",
        "head": "0xe989fe50ed46b6c96d6a116f4ccf77fc0c03c133b14d3fb1158dd7b9c669a875",
        "network": 1337
      }
    }
  }
}
```

the `web3_clientVersion`:

```json
{
  "jsonrpc": "2.0",
  "id": 51,
  "result": "besu/v22.7.2/linux-x86_64/openjdk-java-11"
}
```

Can anyone help me to correctly configure the network to allow free gas transactions?
