### ISSUE TITLE
 The issue of being unable to synchronize when starting Besu via Docker Compose.

### ISSUE THREAD

**Issue by haerker** [hyperledger/besu#6956]
I set network_mode to host , and while the blockchain can run normally, the nodes are not listening on the ports I specified.
like this：

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:36185         0.0.0.0:*               LISTEN      611/node
tcp        0      0 127.0.0.1:6443          0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -
```
As a result, commands like curl are ineffective.
`curl: (7) Failed to connect to localhost port 8545 after 0 ms: Connection refused`
version: "3"
```
Here is a section of my Docker Compose YAML file settings.
services:
  node1:
    image: hyperledger/besu:24.1.2
    container_name: node-1
    network_mode: host
    entrypoint: 
    - /opt/besu/bin/besu
    command: 
    # - --nat-method=AUTO
    - --genesis-file=/root/genesis.json
    - --node-private-key-file=/root/Node-1/data/key
    - --data-path=/root/Node-1/data
    - --min-gas-price=0 
    - --revert-reason-enabled 
    - --rpc-ws-enabled 
    - --rpc-ws-port=8551
    - --rpc-ws-host=0.0.0.0
    - --rpc-ws-api=ADMIN,ETH,NET,PERM,IBFT,WEB3 
    - --host-allowlist="*" 
    - --rpc-http-cors-origins="*"
    - --rpc-http-port=8552
    - --rpc-http-enabled
    - --rpc-http-host=0.0.0.0
    - --rpc-http-api=ADMIN,ETH,NET,PERM,IBFT,WEB3
```

I set network_mode to bridge , The port mapping is correct.
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:36185         0.0.0.0:*               LISTEN      611/node
tcp        0      0 127.0.0.1:6443          0.0.0.0:*               LISTEN      -
tcp6       0      0 :::30303                :::*                    LISTEN      -
tcp6       0      0 :::30306                :::*                    LISTEN      -
tcp6       0      0 :::30304                :::*                    LISTEN      -
tcp6       0      0 :::30305                :::*                    LISTEN      -
tcp6       0      0 :::8558                 :::*                    LISTEN      -
tcp6       0      0 :::8556                 :::*                    LISTEN      -
tcp6       0      0 :::8557                 :::*                    LISTEN      -
tcp6       0      0 :::8554                 :::*                    LISTEN      -
tcp6       0      0 :::8555                 :::*                    LISTEN      -
tcp6       0      0 :::8552                 :::*                    LISTEN      -
tcp6       0      0 :::8553                 :::*                    LISTEN      -
tcp6       0      0 :::8551                 :::*                    LISTEN      -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -
```

but the blockchain cannot discover peer nodes, like this.
```
node-2  | 2024-04-16 08:33:15.854+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
node-1  | 2024-04-16 08:33:16.100+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
node-3  | 2024-04-16 08:33:16.338+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
node-4  | 2024-04-16 08:33:16.348+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
```
How can I ensure that Besu runs perfectly within Docker Compose and that the port listening is set up correctly?
