### ISSUE TITLE
Besu discards Transaction with Zero Gas Price on Free-Gas Network

### ISSUE THREAD

**Issue by unlogicalcode** [hyperledger/besu#7136]
<!-- Have you done the following? -->
<!--   * read the Code of Conduct? By filing an Issue, you are expected to -->  
<!--     comply with it, including treating everyone with respect: -->
<!--     https://github.com/hyperledger/besu/blob/main/CODE_OF_CONDUCT.md -->
<!--   * Reproduced the issue in the latest version of the software -->
<!--   * Read the debugging docs: https://besu.hyperledger.org/private-networks/how-to -->
<!--   * Duplicate Issue check:  https://github.com/search?q=+is%3Aissue+repo%3Ahyperledger/Besu -->
<!-- Note:  Not all sections will apply to all issue types. -->

### Description
As an Besu, I want to deploy a SmartContract on a free-gas Network  so that I can use Besu as a Node for my private Blockchain. 

### Acceptance Criteria
* SmartContract Transaction with gas price of zero can be deployed.

### Steps to Reproduce (Bug)
1. Set up Besu with a private Network with Clique Consensus and zero Base Fee
2. Send a ContractCreation Transaction to Besu
3. See Besu denying the Transaction with Reason `{"jsonrpc":"2.0","id":1,"error":{"code":-32009,"message":"Gas price below configured minimum gas price"}`

**Expected behavior:** Transaction gets accepted an the Contract is created

**Actual behavior:** Besu denying the Transaction with Reason `{"jsonrpc":"2.0","id":1,"error":{"code":-32009,"message":"Gas price below configured minimum gas price"}`

**Frequency:** Every ContractCreation request

### Logs (if a bug)
[besu.log](https://github.com/hyperledger/besu/files/15417996/besu.log)
[genesis.json](https://github.com/hyperledger/besu/files/15418008/genesis.json)

config.toml
```toml
data-path="/data"
rpc-http-enabled=true
rpc-http-api=[
    "ETH",
    "NET",
    "CLIQUE",
]
rpc-http-port=8545
rpc-http-cors-origins=["all"]

host-allowlist=["*"]

genesis-file="/genesis.json"

min-gas-price=0
api-gas-price-max=0

network-id=1337
```
docker-compose.yml
```yaml
---
services:
  besu0:
    image: hyperledger/besu:24.5.1
    command: --config-file=/config.toml --p2p-port=30304 --logging=ALL --min-gas-price=0 --api-gas-price-max=0
    ports:
      - 8545:8545
      - 30304:30304
    networks:
      besu-p2p:
       ipv4_address: 10.5.0.2
    volumes:
      - ./besu-config.toml:/config.toml:ro
      - ./genesis.json:/genesis.json:ro
      - ./node-data:/data:rw
  besu1:
    image: hyperledger/besu:24.5.1
    depends_on:
      - besu0
    command: --config-file=/config.toml --p2p-port=30305 --bootnodes=enode://1c6c4139e6863cee7cfcc55326fea3d91d1e78649cef1a5a969c3c02098deb083d76537655732dfc32e7dae7334fac333429309ff2a0f903f56bfe47451b282b@10.5.0.2:30304 --min-gas-price=0 --api-gas-price-max=0
    ports:
      - 8546:8545
      - 30305:30305
    networks:
      besu-p2p:
       ipv4_address: 10.5.0.3
    volumes:
      - ./besu-config.toml:/config.toml:ro
      - ./genesis.json:/genesis.json:ro
      - ./node-data1:/data:rw
networks:
  besu-p2p:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```

Gas Price Calls from both Nodes in the Cluster: 
```log
joshua@LJ243WK6LG ~/g/o/besu-clique (master)> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":53}' http://127.0.0.1:8545
{"jsonrpc":"2.0","id":53,"result":"0x0"}⏎                                                                                                                                                                                                                                                                                                                                                                                                 joshua@mac~/g/o/besu-clique (master)> 
joshua@mac ~/g/o/besu-clique (master)> 
joshua@mac ~/g/o/besu-clique (master)> curl -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":53}' http://127.0.0.1:8546
{"jsonrpc":"2.0","id":53,"result":"0x0"}⏎                                                                                                                                                                                                                                                                                                                                                                                                 joshua@mac ~/g/o/besu-clique (master)> 
```


### Versions (Add all that apply)
* Software version: [`besu --version`] 24.5.1 docker container
* OS Name & Version: [`cat /etc/*release`] docker
* Kernel Version: [`uname -a`] docker
* Docker Version: [`docker version`] Docker Desktop  4.30.0 (149282), 
```
Server: Docker Desktop 4.30.0 (149282)
 Engine:
  Version:          26.1.1
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       ac2de55
  Built:            Tue Apr 30 11:48:04 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
Contract is deployed with `eth_sendRawTransaction` and works elsewhere.

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options -> attached
* System info - memory, CPU -> Apple MacBook Pro M3
