### ISSUE TITLE
Unable to Sync New Validator Node to Existing Besu QBFT Network on AWS

### ISSUE THREAD

**Issue by jesse-nhatcl** [hyperledger/besu#7598]
### Description

As a developer, I want to add a new validator (only local macOS) to my Besu QBFT network (AWS server) so that the network can scale and be available to add more nodes.

### Acceptance Criteria

- Successfully add the local macOS node to the existing QBFT network on AWS.
- The local node should sync with the AWS nodes and become a validator.

### Steps to Reproduce (Bug)

1. Have 4 nodes running on an AWS server using Docker.
2. On a local macOS machine, run another node with the same genesis file.
3. Set up the bootnodes and configure the node.
4. Run the new node locally.

**Expected behavior:**  
The new node should connect to the existing 4 nodes and start syncing.

**Actual behavior:**  
The new node is unable to find a sync target and keeps logging the following message:

```
node-test-1  | 2024-09-10 18:38:58.113+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
node-test-1  | 2024-09-10 18:39:03.118+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
```

**Frequency:**  
Always

### Logs (if a bug)

Please find the relevant logs from the Besu node below:

```
node-test-1  | 2024-09-10 18:38:58.113+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
node-test-1  | 2024-09-10 18:39:03.118+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 0 peers for usefulness
```

### Versions (Add all that apply)

- Software version: 24.1.1
- Java version: `java -version`
- OS Name & Version:
  - AWS: Ubuntu 20.04.6 LTS
  - macOS: macOS 15.0 (M1)
- Kernel Version (AWS):
  ```
  Linux ip-172-31-41-119 5.15.0-1064-aws #70~20.04.1-Ubuntu SMP Fri Jun 14 15:42:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Docker Version:
  - AWS: 27.0.3
  - macOS: 26.1.4
- Consensus Client & Version: QBFT

#### Besu Setup Info:

**Genesis file** (same for all nodes):

```json
{
  "config": {
    "chainId": 4897,
    "berlinBlock": 0,
    "qbft": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 4,
      "blockreward": "500000000000",
      "miningbeneficiary": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    }
  },
  "nonce": "0x0",
  "timestamp": "0x58ee40ba",
  "extraData": "0xf8a4a00000000000000000000000000000000000000000000000000000000000000000f87e943b0e796c8429cdafc389f1f7d3bd43326f2cd58b940327f4eae23b7627226df94aeb82ef9a8ef79c3394fa575ae1ff3937c976119148fbc7cdc09bbfac5e947b24bee66266f6e7661d1e0272dbb1b43e455bc694f60113244cab20091440ea3dba69f9b33c23d8dd944c1d80775399528806010c41fc95e5071851d75cc080c0",
  "gasLimit": "0x1fffffffffffff",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "alloc": {
    "3AA0dDE27a8626072253219081AE388AEF43Bfb3": {
      "privateKey": "---",
      "comment": "---",
      "balance": "---"
    }
  }
}
```

**AWS Node Config (config.toml):**

```toml
data-path="/usr/app/data"

bootnodes=["enode://b52498f1424ff77ee0bb54ce8e866e42685b948b6b5a9c187064e204f13d3a3e5e7cb3316dba151f6a135251bbd87c824790d1de584e2aad9a193ccf5543db90@34.203.146.198:30303","enode://325908d3a30e2a8e7829385f5d993a77ccde677985e40be1672c02d35e93cc7151e638c8596d4e81e96036f335aa0a8aef80e6b783868c520af10a3df85b3b5b@34.203.146.198:30304","enode://c512bd797354ccc37808ee203fffdbd85fd5411154f4e78826ca48f6e84a718319e838f5c6c1b034869fcda2079ce10db4929635256a8b8a581671dd13fd2405@34.203.146.198:30305","enode://291ffa36577ec77f619d435459e44abacad39c3f876fef55ed8a9484d5ee2d45410b3a8bf90eec3a6aad50f12542d98bc70ec8357091b20d052ab8e849d702b2@34.203.146.198:30306","enode://2fd273c9d25d699d6c7c267873748e16b768b5e99ba32f7b9289d5aafd0a7016df86b7aa2c04b179a4c7fbd457e4ae652f32123e353611b8f47ff93eab137369@34.203.146.198:30307","enode://d8558eb17a11c164a2e00279aa6351cadbe3071cae39bb0d12a7ba33a6719f6805b58cc60486b3d8e9ad8df6082a212a90b5e35cc64c504ff26ab371ca90b39c@34.203.146.198:30308"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT","ADMIN"]
rpc-http-port=8545

rpc-ws-enabled=true
rpc-ws-port=9101
rpc-ws-host="10.5.1.1"

p2p-host="34.203.146.198"
p2p-port=30303

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

genesis-file="/usr/app/genesis.json"

min-gas-price=2000

metrics-push-enabled=true
metrics-push-port=9091
metrics-push-host="prometheus-push"

nat-method="DOCKER"
```

**macOS Node Config (config.toml):**

```toml
data-path="/usr/app/data"

bootnodes=["enode://b52498f1424ff77ee0bb54ce8e866e42685b948b6b5a9c187064e204f13d3a3e5e7cb3316dba151f6a135251bbd87c824790d1de584e2aad9a193ccf5543db90@34.203.146.198:30303","enode://325908d3a30e2a8e7829385f5d993a77ccde677985e40be1672c02d35e93cc7151e638c8596d4e81e96036f335aa0a8aef80e6b783868c520af10a3df85b3b5b@34.203.146.198:30304","enode://c512bd797354ccc37808ee203fffdbd85fd5411154f4e78826ca48f6e84a718319e838f5c6c1b034869fcda2079ce10db4929635256a8b8a581671dd13fd2405@34.203.146.198:30305","enode://291ffa36577ec77f619d435459e44abacad39c3f876fef55ed8a9484d5ee2d45410b3a8bf90eec3a6aad50f12542d98bc70ec8357091b20d052ab8e849d702b2@34.203.146.198:30306","enode://2fd273c9d25d699d6c7c267873748e16b768b5e99ba32f7b9289d5aafd0a7016df86b7aa2c04b179a4c7fbd457e4ae652f32123e353611b8f47ff93eab137369@34.203.146.198:30307","enode://d8558eb17a11c164a2e00279aa6351cadbe3071cae39bb0d12a7ba33a6719f6805b58cc60486b3d8e9ad8df6082a212a90b5e35cc64c504ff26ab371ca90b39c@34.203.146.198:30308"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","QBFT"]
rpc-http-port=8555

rpc-ws-enabled=true
rpc-ws-port=9201
rpc-ws-host="10.5.1.1"

p2p-host="0.0.0.0"
p2p-port=30403

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

genesis-file="/usr/app/genesis.json"

min-gas-price=2000

nat-method = "DOCKER"

```

**Docker Compose File for AWS Node 1:**

```yaml
version: "3"

services:
  node:
    image: hyperledger/besu:24.1.1-SNAPSHOT
    container_name: node-1
    volumes:
      - .:/usr/app
    command: --config-file=/usr/app/config.toml
    ports:
      - 8545:8545 # rpc-http
      - 30303:30303 # p2p (TCP)
      - 9101:9101 # rpc ws

volumes:
  .:
```

**Docker Compose File for AWS all node:**
```yaml
version: "3"

services:
  node-1:
    extends:
      file: "./node-1/docker-compose.yml"
      service: node
    networks:
      besu-network:
        ipv4_address: 10.5.1.1

  node-2:
    extends:
      file: "./node-2/docker-compose.yml"
      service: node
    networks:
      besu-network:
        ipv4_address: 10.5.1.2

  node-3:
    extends:
      file: "./node-3/docker-compose.yml"
      service: node
    networks:
      besu-network:
        ipv4_address: 10.5.1.3

  node-4:
    extends:
      file: "./node-4/docker-compose.yml"
      service: node
    networks:
      besu-network:
        ipv4_address: 10.5.1.4

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
  qbftnetwork_besu-network:
    external: true
```
**Docker Compose File for macOS Node:**

```yaml
version: "3"

services:
  node:
    image: hyperledger/besu:24.1.1-SNAPSHOT
    container_name: node-test-1
    volumes:
      - .:/usr/app
    command: --config-file=/usr/app/config.toml
    ports:
      - 8555:8555 # rpc-http
      - 30403:30403 # p2p (TCP)
      - 9201:9201 # rpc ws

volumes:
  .:
```
